### ISSUE TITLE
Wont import dll on Windows 

### ISSUE THREAD

**Issue by LexSong** [cjrh/vim-conda#10]
Please see #11

**Comment by LexSong** [comment]
#11

**Comment by cjrh** [comment]
Hi @LexSong!

Could you give me a little bit more detail?  Is the problem with code completion?

**Comment by LexSong** [comment]
Yes, if you install some package like `numpy`, conda will also install `mkl`, which are dll files, installed to `Library\bin`.
In original `activate.bat`, conda also add `Library\bin` to `$PATH`:

    ECHO Activating environment "%CONDA_DEFAULT_ENV%"...
    SET "PATH=%CONDA_DEFAULT_ENV%;%CONDA_DEFAULT_ENV%\Scripts;%CONDA_DEFAULT_ENV%\Library\bin;%PATH%"
    IF "%CONDA_NEW_NAME%"=="" (
       REM Clear CONDA_DEFAULT_ENV so that this is truly a "root" environment, not an environment pointed at root
       SET CONDA_DEFAULT_ENV=
       ) ELSE (
       SET "PROMPT=[%CONDA_NEW_NAME%] %PROMPT%"
    )

without `Library\bin`, code completion won't work
`:py import numpy` will also fail

**Comment by cjrh** [comment]
Ok, that's perfect info, thank you.

**Comment by cjrh** [comment]
Fixed with #11.
