### ISSUE TITLE
Suppress Message on Startup

### ISSUE THREAD

**Issue by machbio** [cjrh/vim-conda#16]
Is there a way to suppress the following message that is printed on startup - 

```
Conda env deactivated.
Activated env: py33
Press ENTER or type command to continue
```
 It will help, if there was an option that I can define in the .vimrc file to hide/display the message.

**Comment by cjrh** [comment]
Great idea! If you make a PR for this I'll merge it 👍

**Comment by machbio** [comment]
I have no experience with vim plugins - have you used any vim variable - so I can follow suit and make the changes.

**Comment by machbio** [comment]
@cjrh  I have added the pull request #17 for suppressing the message

**Comment by cjrh** [comment]
I've merged the PR.  I've also created a new file in the root called `CONTRIBUTORS`, and I've added your name.  I hope that's ok.  If not I can remove it, just let me know.

Thanks again!

**Comment by nikhilpriyatam** [comment]
I had a similar message while starting vim. The following command got rid of the message for me.
source deactivate <Environment Name>

However my $PYTHON3_PATH is set to the conda environment in .bashrc and .profile, so autocomplete plugins like jedi-vim work without any hassles. Hope this helps.
