### ISSUE TITLE
Massive error log on startup

### ISSUE THREAD

**Issue by hholst80** [cjrh/vim-conda#18]
I am using Pathogen and Vim 7.4 (patch 1...1689) and Anaconda w/ Python 3. 
vim-conda 838f582cc0829b5b0ba5852fa2d103907faec486

```
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 16 2016 10:50:38)
Included patches: 1-1689
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
+balloon_eval    +float           +mouse_urxvt     +tcl
+browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
+clientserver    +iconv           +packages        +toolbar
+clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             +perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xsmp_interact
+emacs_tags      +mouseshape      +startuptime     +xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        +mouse_gpm       -sun_workshop    +xpm
+extra_search    -mouse_jsbterm   +syntax          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm
```

```
hholst@fb-hholst3:~$ which python
/home/hholst/anaconda3/bin/python
hholst@fb-hholst3:~$ which python2
/usr/bin/python2
hholst@fb-hholst3:~$ which python3
/home/hholst/anaconda3/bin/python3
hholst@fb-hholst3:~$ python --version
Python 3.5.1 :: Anaconda custom (64-bit)
hholst@fb-hholst3:~$ 
```

```
E133: :return not inside a function
line   20:
E488: Trailing characters:         # Needed to avoid
line   21:
E488: Trailing characters:         # When launching gvim.exe from a CMD shell. (gvim from icon seems
line   22:
E488: Trailing characters:         # fine!?)
line   23:
E488: Trailing characters:         # See also: http://bugs.python.org/issue3905
line   24:
E488: Trailing characters:         # stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
line   25:
E492: Not an editor command:         stdin=PIPE, stderr=PIPE)
line   28:
E492: Not an editor command: def vim_conda_runpyshell(cmd):
line   29:
E133: :return not inside a function
line   30:
E492: Not an editor command:         executable=os.getenv('SHELL'),
line   31:
E492: Not an editor command:         stdin=PIPE, stderr=PIPE)
line   34:
E492: Not an editor command: def get_conda_info_dict():
line   36:
E492: Not an editor command:     {
line   42:
E492: Not an editor command:       ],
line   55:
E492: Not an editor command:       ],
line   58:
E492: Not an editor command:       ],
line   62:
E492: Not an editor command:       ],
line   71:
E492: Not an editor command:     }
line   73:
E492: Not an editor command:     output = vim_conda_runshell('conda info --json')
line   74:
E133: :return not inside a function
line   77:
E492: Not an editor command: def insert_system_py_sitepath():
line   79:
E492: Not an editor command:     embedded Python's sys.path. This is for Jedi-vim code completion. """
line   80:
E492: Not an editor command:     cmd = "import site, sys, os; sys.stdout.write(os.path.pathsep.join(site.getsitepackages()))"
line   81:
E33: No previous substitute regular expression
line   82:
E488: Trailing characters:     # The following causes errors. Jedi vim imports e.g. hashlib
line   83:
E488: Trailing characters:     # from the stdlib, but it we've added a different stdlib to the
line   84:
E488: Trailing characters:     # embedded sys.path, jedi loads the wrong one, causing errs.
line   85:
E488: Trailing characters:     # Looks like we should only load site-packages.
line   86:
E488: Trailing characters:     # if len(sitedirs) > 0:
line   87:
E488: Trailing characters:     #     libdir = os.path.dirname(sitedirs[0])
line   88:
E488: Trailing characters:     #     if libdir not in sys.path:
line   89:
E488: Trailing characters:     #         sys.path.insert(0, libdir)
line   90:
E121: Undefined variable: sitedirs
E15: Invalid expression: sitedirs:
line  420:
E171: Missing :endif
Press ENTER or type command to continue
```

**Comment by cjrh** [comment]
Hi Henrik

I recently merged a pull request that had print statements without parentheses.  I think this might be causing the crash.  I don't personally use vim compiled against Python 3 so I never pick these things up.

I've made a fix in 9977b0a, could you please try to update and see if that works for you?   If not, it would be great for you to check which older commit of vim-conda _did_ work for you, so that we can figure out where the problem began.

Good luck!

**Comment by cjrh** [comment]
I had another look at the pull request I merged.  The `print` statements were not modified by the PR, they already lacked parens.  So it seems unlikely to have made a difference.

**Comment by cjrh** [comment]
In your vim config, I see `-python` which means no Python 2 support.  Pretty much the entire vim-conda plugin is executed with `python` blocks.  In your vim, I'm guessing that if you go into command mode and try to run `py 1` you get an error, whereas if you run `py3 1` you get 1 returned?  If this is the case, there probably isn't much we can do.  If you look inside the source code for `vim-conda.vim`, you will see a bunch of Python sections that begin with

```
python << EOF
    blah
    blah
    blah
    blah
EOF
```

That `python` reference in the `python << EOF` line might already be causing the crash.  Perhaps for Python 3 it should say `python3 << EOF` instead?

**Comment by cjrh** [comment]
Ok, I'm feeling somewhat confident that the main issue is that vim-conda is explicitly calling `python` in all those embedded blocks.  This is not going to work for Python 3, since there are [explicit commands](http://vimdoc.sourceforge.net/htmldoc/if_pyth.html#python3) for Python 3.

This has been bugging me for a long time, and I guess it's time to do something about it!

I'm going to refactor vim-conda to remove all the Python out of the vim file and into a separate Python file, and instead call it with the `pyfile` command.  Doing it like this will allow me to check whether to call either `pyfile` or `py3file` (using, e.g., `has('python')` and `has('python3')`) and should therefore make it possible to call both.  This obviously also means that all the  Python code will have to be compatible with both 2 and 3.

**Comment by hholst80** [comment]
I tried replacing all the `python <<EOF` with `py3 <<EOF` and added a few hacks for str/bytes objects but I got this:

![image](https://cloud.githubusercontent.com/assets/6200749/17053697/7af9eda8-5003-11e6-8a4a-efadacc53cf3.png)

```
diff --git a/plugin/vim-conda.vim b/plugin/vim-conda.vim
index ae3dfcc..f52e5f0 100644
--- a/plugin/vim-conda.vim
+++ b/plugin/vim-conda.vim
@@ -78,7 +79,7 @@ def insert_system_py_sitepath():
     """ Add the system $PATH Python's site-packages folders to the
     embedded Python's sys.path. This is for Jedi-vim code completion. """
     cmd = "import site, sys, os; sys.stdout.write(os.path.pathsep.join(site.getsitepackages()))"
-    sitedirs = vim_conda_runpyshell(cmd).split(os.path.pathsep)
+    sitedirs = vim_conda_runpyshell(bytes(cmd, 'utf-8')).split(bytes(os.path.pathsep, 'utf-8'))
@@ -87,6 +88,7 @@ def insert_system_py_sitepath():
     #     libdir = os.path.dirname(sitedirs[0])
     #     if libdir not in sys.path:
     #         sys.path.insert(0, libdir)
+    sitedirs = [bytes(sitedir) for sitedir in sitedirs]
     for sitedir in sitedirs:
         if sitedir not in sys.path:
             sys.path.insert(0, sitedir)
@@ -122,6 +124,7 @@ else:
         # See also: http://bugs.python.org/issue3905
         # stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
         stdin=subprocess.PIPE, stderr=subprocess.PIPE)
+    output = ''.join(chr(int(x)) for x in output)
```

**Comment by hholst80** [comment]
The `YouCompleteMe` package is probably a good reference to look at for figuring out how to deal with Vim python (2.x) and python 3 in the same vim package.

**Comment by cjrh** [comment]
> I tried replacing all the python << EOF with python3 << EOF and added a few hacks for str/bytes objects but I got this:

Thanks for taking a look at this.  That error you see is coming from YouCompleteMe, but I'm not sure what it means.

**Comment by cjrh** [comment]
Actually, I'm wrong, the original exception was _RuntimeError: dict size changing during iteration_, not the YCM `ImportError`.

**Comment by cjrh** [comment]
Ok I found the problem, it's here: 

https://github.com/cjrh/vim-conda/blob/master/plugin/vim-conda.vim#L375

The code is:

```python
for key, value in envnames.items():
    if value == default_prefix:
        current_env = key
        # Don't provide current_env as an option for user
        del envnames[key]
```

This code was a bit lazy on my part.  I just wanted to remove the entry for the current prefix, but of course in Python 3 `dict` methods return views much of time.    

As you can see above I've made a fix in cf901d9.  I have not tested it though, so if you could let me know whether that problem goes away that would great.

**Comment by hholst80** [comment]
I'm heading to island for a week but I sent a mail to myself to have a check as soon as I get back. Thanks for looking into it!

**Comment by cjrh** [comment]
@hholst80 No problem, and thanks for your work 👍

**Comment by machbio** [comment]
@cjrh I had thought about this,  but then I thought you only supported python 2, sorry about this

**Comment by cjrh** [comment]
@machbio On my platform vim links against either Python 2 or 3, but not both, so I had to make a choice and I chose 2.  (and though I play with neovim, which has facilities for working with both, I haven't wholescale switched yet).   On the other hand, all the Python code I write, at least for the past two years is in Python 3.   I know that it's a problem, but it's not an easy problem unfortunately.  

YouCompleteMe has a solution for this problem: it calls Jedi via an intermediate HTTP server, and that server calls the Python env of your choice to provide completion in that environment.  However, I am wary to recommend (and/or build direct integration with) YCM right now, because it can be tricky to install.

**Comment by hholst80** [comment]
There are still some problems with string/byte (and utf??) miss matching. I tried fixing some of them but it's probably better if someone who's got more time to look into the problem deeply have a look instead of me hacking something together. 

An instance of such error can look like:

```
Error detected while processing function <SNR>16_CondaChangeEnv:
line 58:
Traceback (most recente call last):
  File <string>, line 41, in <module>
TypeError: sequence item 0: expected str instance, bytes found
```

**Comment by cjrh** [comment]
I'm thinking that to work on this issue properly will require using both a vim compiled against Python 2, and another vim compiled against Python 3, to make sure that this plugin works in both.

**Comment by hstarmans** [comment]
I have checked the command:
sitedirs = vim_conda_runpyshell(cmd).split(os.path.pathsep)
should become -->
sitedirs = vim_conda_runpyshell(cmd).split(os.path.pathsep.encode())

**Comment by cjrh** [comment]
@hstarmans Thanks for looking at this! Would you be able to submit the changes in a pull request?  Also, have you checked that your changes work on both Python 2 and 3?

**Comment by hstarmans** [comment]
@cjrh The code is not Python 2 and Python 3 compatible. This is, however, easy to fix and test. Several other vim plugins have tackled this issue.
Do you have any experience with using vim-conda with [YouCompleteMe](https://github.com/Valloric/YouCompleteMe)?
It uses a Jedi-based completion engine for Python 2 and 3 (using the JediHTTP wrapper) or can I only use jedi-vim?
I will submit a pull request but need to test the plugin a bit with vim-ipython and YouCompleteMe and / or jedi-vim .

**Comment by cjrh** [comment]
@hstarmans I've added you as a collaborator to this project.  I have very little free time available right now and I don't want to prevent any progress by being unavailable.

This plugin code must be 2/3 compatible because a lot of people use vim compiled against one of the two python versions.  That matters here because the python code interacts directly with vim.

Regarding compatibility with YouCompleteMe, I think you would have to add a feature in vim-conda to detect whether YouCompleteMe is installed, and then when a new conda env is activated, you'd have to restart either the YCM server or the JediHTTP wrapper that YCM uses.  You would probably also have to setup your `.vimrc` to contain

```
let g:ycm_python_binary_path = 'python'
```

so that the modified `$PATH` (which vim-conda will modify when an env is changed) will allow JediHTTP to detect the new python.

Anyway, you have push rights on this repo now, good luck!

**Comment by hstarmans** [comment]
@cjrh I am also pretty busy right now, but will try to fix these minor additions. I will first try to make the code python 2 and 3 compatible and then fix the YouCompleteMe compatibility.

**Comment by cjrh** [comment]
Here I found a specific command for `RestartServer`, although it may still be easier to just configure the ycm binary path setting to `'python'` and just restart JediHTTP. You'll probably have to test out what works better.

Anyway, here is the link to the YCM setting: https://github.com/Valloric/YouCompleteMe#the-restartserver-subcommand
