### ISSUE TITLE
msg_suppress not defined

### ISSUE THREAD

**Issue by JimBiardCics** [cjrh/vim-conda#20]
If I start vim and the CONDA_DEFAULT_ENV environment variable is not defined, when I attempt to activate an environment using :CondaChangeEnv, I get an error message complaining that the global variable msg_suppress is not defined in the conda_activate function. Looking at the vim-conda.vim file, I see that this is true - the variable is only set if CONDA_DEFAULT_ENV is already set. The msg_suppress global variable needs to be set no matter what.

**Comment by MerDane** [comment]
I also got this issue, but I don't know how to fix it, can you more specifically

**Comment by JimBiardCics** [comment]
@MerDane, there are three ways. If you set a conda environment before running vim, then you'll be fine. (This only works on the command line.) If you set CONDA_DEFAULT_ENV in your .bashrc, you'll be fine. Or if you want, you can modify the vim-conda.vim file by inserting the code block
```
import vim
msg_suppress = int(vim.eval('exists("g:conda_startup_msg_suppress")'))
if msg_suppress:
    msg_suppress = int(vim.eval('g:conda_startup_msg_suppress'))
```
before line 344.

**Comment by gessulat** [comment]
Had the same issue, but your snippet fixed it.

**Comment by cjrh** [comment]
@JimBiardCics Your fix code has been added at line 308.  Ok to close this issue?

**Comment by JimBiardCics** [comment]
Yes!
