### ISSUE TITLE
python 2 & 3 compatibility

### ISSUE THREAD

**Issue by jfishe** [cjrh/vim-conda#21]
I created a fork to add compatiblity for both flavors of python. It could use some more testing since I don't use python 2 much any more.

Let me know if you'd like a pull request.

Thanks for the great script. I learned alot updating it for my needs.

**Comment by hstarmans** [comment]
@jfishe i have looked at the code. It looks like this could solve the issues. I am willing to accept it so make a pull request. I know @cjrh  does not have a lot of time and I am working on a  [Kickstarter](https://www.kickstarter.com/projects/884006515/1358551124?token=d94c0565 )

**Comment by cjrh** [comment]
For sure make a pull request 👍
