### ISSUE TITLE
Bug: plugin.vim should import vim

### ISSUE THREAD

**Issue by cjrh** [cjrh/vim-conda#6]
Currently plugin.vim relies on some other script importing the python vim plugin.  To fix this just add

```python
import vim
```
To the top imports in the plugin.

**Comment by patelkunal** [comment]
Error detected while processing function <SNR>17_SetCondaPlainPath:
line   34:
Traceback (most recent call last):
  File "<string>", line 32, in <module>
NameError: name 'vim' is not defined
line   35:
E121: Undefined variable: l:temppath
E15: Invalid expression: l:temppath
Press ENTER or type command to continue

**Comment by cjrh** [comment]
Hi @patelkunal, I added `import vim` in 	9e3d367, please try again.
